### ISSUE TITLE
CI testflight failing - docker_meta.txt: No such file or directory

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/postgresql-docker-boshrelease#22] opened 2016-04-02 23:09 UTC
As discovered in #19 

```
Seeing the following log errors on failing job:

==> /var/vcap/sys/log/monit/postgresql_images.err.log <==
+ for image in '/var/vcap/packages/*_image/*.tgz'
++ dirname /var/vcap/packages/cfcommunity_postgresql_9_3_image/image.tgz
+ img_dir=/var/vcap/packages/cfcommunity_postgresql_9_3_image
++ cat /var/vcap/packages/cfcommunity_postgresql_9_3_image/docker_meta.txt
cat: /var/vcap/packages/cfcommunity_postgresql_9_3_image/docker_meta.txt: No such file or directory
+ docker_tag=

==> /var/vcap/sys/log/monit/monit_debugger.install_ctl.log <==
MONIT-DEBUG exit code 1

==> /var/vcap/sys/log/cf-containers-broker/route-registrar.stdout.log <==
{"timestamp":"1459638444.436142683","source":"Route Registrar","message":"Route Registrar.Error connecting to NATS","log_level":1,"data":{"error":"dial tcp 10.244.0.6:4222: i/o timeout"}}

==> /var/vcap/sys/log/cf-containers-broker/route-registrar.stderr.log <==
panic: Failed to connect to NATS bus.
```

**Comment by bodymindarts** [comment] 2016-04-04 07:14
@goehringc does [your commit](https://github.com/cloudfoundry-community/postgresql-docker-boshrelease/commit/2060c2fcb24ee5b47c36c6db0cc02515b6b6dc7d) fix this? Can we close this issue?

**Comment by goehringc** [comment] 2016-04-04 12:30
@bodymindarts it should, but I haven't been able to fully verify as I'm having trouble with a successful pipeline run.  @drnic Any ideas with http://ci.vsphere.starkandwayne.com/pipelines/postgresql-docker-boshrelease/jobs/bump-layers/builds/11

**Comment by bodymindarts** [comment] 2016-04-04 12:46
@goehringc we have been having that problem with the `Cannot mknod: Operation not permitted` on our vsphere concourse in multiple pipelines and have not yet discovered the root cause. Re-triggering the job just now worked and has turned all jobs green.

Since the deployment went through you're fix has probably worked.

**Closed as completed** 2016-04-04 12:49 UTC
